version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
- cmd: git config --global core.autocrlf true
install:
# Install repo specific stuff here
before_build:
#- cd TestEnvironment
# Display .NET Core Version
- cmd: dotnet --version
# Display normal restore test
- dotnet restore ./TestEnvironment/TestEnvironment.csproj
# Display minimal restore test
#- cmd: dotnet restore ./TestEnvironment/TestEnvironment.csproj --verbosity m
build_script:
# output will be in ./TestEnvironment/bin/Debug/net472
- cmd: dotnet publish ./TestEnvironment/TestEnvironment.csproj
test_script:
# restore packages for our unit tests
- cmd: dotnet restore ./TestEnvironmentUnitTests/TestEnvironmentUnitTests.csproj --verbosity m
# run the unit tests (requires changing into the test directory)
- cmd: cd TestEnvironmentUnitTests
- cmd: dotnet test
on_finish:
# any cleanup in here
deploy: off